package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// shellHookFileName holds the aliases `./do shell-hook` generates.
const shellHookFileName = stateDirectory + "/shell.sh"

func runBootstrap(p *project, args []string) error {
	withBrowsers := false
	for _, arg := range args {
		switch arg {
		case "--browsers":
			withBrowsers = true
		default:
			return fmt.Errorf("unknown flag for bootstrap: %q", arg)
		}
	}
	return p.bootstrap(withBrowsers)
}

func (p *project) bootstrap(withBrowsers bool) error {
	if err := p.ensureBootstrapped(); err != nil {
		return err
	}

	if withBrowsers {
		if err := p.ensurePlaywrightBrowser(); err != nil {
			return err
		}
	}

	info("bootstrap complete — the toolchain under %s/, the frontend under web/node_modules/",
		stateDirectory)
	return nil
}

// ensureBootstrapped makes the checkout ready to run: the state directory, and
// a web/node_modules that matches the lockfile.
//
// There is no "have we bootstrapped yet" flag. The toolchain is the shim's
// business — it runs `mise install` before every command, idempotently — and
// the frontend install compares the lockfile it recorded against the one on
// disk. Both questions answer themselves; a stamp for the pair would be a
// third thing to keep true, and the first `./do up` after a `git pull` would
// pay a full `npm ci` for a lockfile that had not changed.
func (p *project) ensureBootstrapped() error {
	if err := p.ensureStateDirectory(); err != nil {
		return err
	}
	return p.ensureFrontendDependencies()
}

func runShellHook(p *project, args []string) error {
	write := false
	for _, arg := range args {
		switch arg {
		case "--write":
			write = true
		default:
			return fmt.Errorf("unknown flag for shell-hook: %q", arg)
		}
	}

	checkout, err := filepath.EvalSymlinks(p.directory)
	if err != nil {
		return fmt.Errorf("resolving the checkout path: %w", err)
	}

	// "$@" on each: a shell function drops the arguments it is not told to
	// pass on, silently, so `yagit-up --new-token` used to run a plain
	// `./do up` — reporting the leaked token it was typed to replace, with
	// exit status 0.
	contents := fmt.Sprintf(`# Generated by ./do shell-hook — do not edit.
yagit-up()   { (cd %q && ./do up "$@"); }
yagit-down() { (cd %q && ./do down "$@"); }
yagit-logs() { (cd %q && ./do logs "$@"); }
`, checkout, checkout, checkout)

	if err := p.writeStateFile(shellHookFileName, []byte(contents)); err != nil {
		return err
	}
	path := p.path(shellHookFileName)

	line := fmt.Sprintf("source %q", path)
	if !write {
		printShellHookHelp(line, path)
		return nil
	}

	profile, err := shellProfilePath()
	if err == nil {
		err = appendLine(profile, line)
	}
	if err != nil {
		// The line is what the person came for. Refusing to guess at a profile
		// — or failing to write to it — is no reason to withhold it.
		printShellHookHelp(line, path)
		return err
	}

	fmt.Printf("\n  Added to %s. Open a new terminal, or:\n\n    source %s\n\n", profile, profile)
	return nil
}

func printShellHookHelp(line, path string) {
	fmt.Printf("\n  Add this line to your shell profile:\n\n    %s\n\n", line)
	fmt.Printf("  Or run aliases now:\n\n    source %s\n\n", path)
}

// appendLine adds one line to a file, and only ever adds.
//
// It appends rather than rewriting. Reading a shell profile into memory and
// writing it back would put every line the person has ever written at the
// mercy of an interrupt or a full disk between the truncate and the write;
// O_APPEND touches none of the existing bytes, and an interrupted append loses
// only the line this program was adding.
func appendLine(path, line string) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	if containsLine(string(existing), line) {
		return nil
	}

	// A profile whose last line has no newline would otherwise have this one
	// glued onto the end of it.
	addition := line + "\n"
	if len(existing) > 0 && !strings.HasSuffix(string(existing), "\n") {
		addition = "\n" + addition
	}

	// 0o600 applies only when this creates the file. An existing profile keeps
	// the mode it has: this is the person's file, not ours.
	file, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("opening %s: %w", path, err)
	}
	defer func() {
		if err := file.Close(); err != nil {
			warn("closing %s: %s", path, err)
		}
	}()

	if _, err := file.WriteString(addition); err != nil {
		return fmt.Errorf("appending to %s: %w", path, err)
	}
	return nil
}

// shellProfilePath names the file the shell in use actually reads.
//
// It refuses rather than guessing. $SHELL is unset in plenty of
// non-interactive contexts, and fish, nushell and the rest read neither
// ~/.bashrc nor ~/.zshrc — writing there would report success about a line
// that is never sourced, which is worse than saying so. The line to add is
// printed either way, so a refusal here still leaves the person one paste from
// done.
func shellProfilePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("finding your home directory: %w", err)
	}

	shell := os.Getenv("SHELL")
	if shell == "" {
		return "", fmt.Errorf("SHELL is not set, so there is no profile to write to.%s", indent(
			"Add the line printed above to your shell's startup file yourself."))
	}

	switch filepath.Base(shell) {
	case "bash":
		return filepath.Join(home, ".bashrc"), nil
	case "zsh":
		return filepath.Join(home, ".zshrc"), nil
	default:
		return "", fmt.Errorf("SHELL is %q, and --write knows bash and zsh only.%s", shell, indent(
			"Add the line printed above to that shell's startup file yourself."))
	}
}

func containsLine(haystack, needle string) bool {
	for line := range strings.Lines(haystack) {
		if strings.TrimSpace(line) == needle {
			return true
		}
	}
	return false
}
